### ISSUE TITLE
Can you stub Segment::Analytics#track?

### ISSUE THREAD

**Issue by JoshSmith** [segmentio/analytics-ruby#105]
I'm trying to `expect_any_instance_of(Segment::Analytics).to receive(:track)` in tests and am receiving the error `Segment::Analytics does not implement #track`. I have also passed in the `stub` option.

Is this normal, or to be expected somehow?

**Comment by sperand-io** [comment]
@ndhoule can you weigh in here?

**Comment by JoshSmith** [comment]
Bump in the night.

**Comment by monfresh** [comment]
@JoshSmith That error means your test is not configured properly. If you post the following things, I'll try to help you:

- Your Gemfile entry for `analytics-ruby`
- How you are calling the `track` method in your app
- Your test

**Comment by JoshSmith** [comment]
Closing because likely user error and I'm not using this library now.

**Comment by axsuul** [comment]
`Segment::Analytics` depends on `method_missing` to proxy its methods. So you will need to do something like this:

```ruby
expect_any_instance_of(Segment::Analytics).to receive(:method_missing).with(:track, hash_including(event: "Logged Out", properties: { email: "foo@bar.com" }))
```

**Comment by dangerouse** [comment]
In the current version, I'm finding that the method is called on the `Segment::Analytics` class itself. So this is doing the job:
```ruby
  allow(Analytics).to receive :track
```

**Comment by vinayak-mehta** [comment]
@aliceclv and I tried the `expect_any_instance_of` directly on the `Segment::Analytics::Client` and it works too:

```ruby
expect_any_instance_of(Segment::Analytics::Client).not_to receive(:track).with(
  hash_including(
    event: 'Logged Out',
    properties: {
      email: "foo@bar.com"
    }
  )
)
```

It's more readable in case someone doesn't know about how the `method_missing` setup works.
