### ISSUE TITLE
Segment module conflict with our application Segment class

### ISSUE THREAD

**Issue by lou** [segmentio/analytics-ruby#112]
We have a model in our application named `Segment` so I can't use this gem.
Maybe you can rename it `SegmentIo` or whatever less generic.
Thank you,

**Comment by lcpriest** [comment]
I'm running a fork here:
https://github.com/advocately/analytics-ruby

**Comment by f2prateek** [comment]
I do understand your problem  but I don't think it's practical to rename the project. Any term we use could cause a conflict. There's a good discussion here https://github.com/rails/journey/issues/49.

We could offer a suggestion if people do run into a conflict though. @rohitpaulk @nettofarah  - any suggestions?

**Comment by f2prateek** [comment]
@rohitpaulk any workarounds for folks that run into a conflict?

**Comment by lcpriest** [comment]
I just run a fork where I batch renamed Segment to Segmentio.
  

  
  

  
  
>

**Comment by nettofarah** [comment]
I guess you could do something like:
`gem segment, require: false` in your Gemfile

And then alias either your `Segment` class or our module.

**Comment by rohitpaulk** [comment]
This is tricky, and I don't have a good answer. 

Relevant reading: https://github.com/rails/journey/issues/49 (as @f2prateek pasted above), and https://stackoverflow.com/questions/17585502/how-can-i-rename-a-ruby-library-modules-namespace. 

I don't think that aliasing will work at the moment, as we still do reference `Segment` within classes, like [here](https://github.com/segmentio/analytics-ruby/blob/master/lib/segment/analytics.rb#L21). We _should_ be able to avoid all such calls though. 

If we manage to avoid such usages, then here's how aliasing could work: 

```ruby
require "segment/analytics"
SegmentIO = Segment
Object.send(:remove_const, Segment)

# Now, Segment can be defined
```

This is still a hacky solution though, you'd have to make sure that all of this runs **before** your `Segment` class is defined. 

If this seems acceptable, I could make the changes and test this out.

**Comment by rohitpaulk** [comment]
Closing as stale. Haven't seen much activity on this, the workaround is tricky to implement, and renaming our project isn't practical.

**Comment by gottfrois** [comment]
Just for the sake of this issue, I ran into the same issue.

**Comment by phmulin** [comment]
Agreed. I'm running into the same issue and considering to simply drop use of segment.com
