### ISSUE TITLE
Experiencing some encoding issues

### ISSUE THREAD

**Issue by pawel2105** [segmentio/analytics-ruby#113]
Gem: `analytics-ruby (2.0.13)`

I've got a problem where single apostrophes are being escaped on Segment when being provided with an unescaped string. In other words:

    @analytics = Segment::Analytics.new(Rails.application.config_for(:segment))
    @analytics.track({
      user_id: User.first.email,
      event: 'TEST',
      properties: {
        company_name: Company.last.name
      }
    })

When I open up my console:

    >> Company.last.name
    => "Pawel's company"

The result as seen in the debugger of the Segment dashboard:

     company_name: 'Pawel\'s company'

**Comment by f2prateek** [comment]
This might just be in the "pretty" view, which is just a guess as to how the code looks. I think the raw view should show things as expected (i.e. "Pawel's company"). I will need to confirm though so keeping it open.

**Comment by f2prateek** [comment]
Tracking internally https://segment.atlassian.net/browse/LIB-107

**Comment by rohitpaulk** [comment]
Confirmed:

**Raw:**

![screen shot 2017-12-12 at 12 09 16 pm](https://user-images.githubusercontent.com/3893573/33870750-58d0047a-df35-11e7-8bcb-90e96798918a.png)

**Pretty:**

![screen shot 2017-12-12 at 12 09 08 pm](https://user-images.githubusercontent.com/3893573/33870751-590301f4-df35-11e7-96ae-673287737f87.png)
