### ISSUE TITLE
What's the best way to increment and/or update user profile data?

### ISSUE THREAD

**Issue by antonielcm** [segmentio/analytics-ruby#124]
Hello guys!

I'm working on a kind of e-commerce, and after the first user order, I want to save some data to the profile (fields like first_order_date, etc.).

What's the best way to do it? The only way I found was use the `identify` method, passing the fields in traits. It's the best way or there's another?

And about the increment, I need to control it in my side or there's a method for it? (I didn't found it on documentation) Because, for example, after each order I want to add the order value to the `revenue` field.

Thank you for now! :wink:

**Comment by lcpriest** [comment]
@antonielcm have you checked out the [Ecommerce spec](https://segment.com/docs/spec/ecommerce/v2/)? It even covers how you would send revenue data.

You might actually want a mix of several actions. 
`identify` is great for sending attributes about the user, whereas `track` can be used to send data about individual orders (i.e. sending `Order completed` would allow you to count the number of orders a user has sent, as well as `first_occurred_at` and `last_occurred_at`.

**Comment by antonielcm** [comment]
@lcpriest oh yeah, I think it will solve my problem. Thanks! 

Also, how can I store the `first_occurred_at` and `first_occurred_at` using this spec?

**Comment by nettofarah** [comment]
Hey, @antonielcm.
This repo is specific to the analytics-ruby library.

You should be able to find answers to this sort of questions in our specs page: https://segment.com/docs/spec/

If not, feel free to contact our support.
