### ISSUE TITLE
[Ecommerce Spec] Dealing with revenue in checkout

### ISSUE THREAD

**Issue by antonielcm** [segmentio/analytics-ruby#125]
Hi guys! I have some questions about the `revenue` property during the checkout: I'm using Mixpanel, and when I track the `Checkout Started` event, the spec tells me to send the `revenue` property. But, when I do it, it changes the user's revenue, and I can't do it because during the checkout the user didn't buy anything (the user can abandon the checkout process).

So, I want to change the revenue only after the `Order Completed`, how can I deal with it?

**Comment by antonielcm** [comment]
:up:

**Comment by nettofarah** [comment]
Hey, @antonielcm.
This repo is specific to the analytics-ruby library.

You should be able to find answers to this sort of questions in our specs page: https://segment.com/docs/spec/

If not, feel free to contact our support.
