### ISSUE TITLE
Using a wrong write_key doesn't trigger an error? 

### ISSUE THREAD

**Issue by rohitpaulk** [segmentio/analytics-ruby#136]
I deliberately tried copying a wrong write_key, and the library didn't call `on_error`. 

```ruby
require "bundler"
Bundler.require(:default)

require "segment/analytics"

analytics = Segment::Analytics.new(
  write_key: "this_is_wrong",
  on_error: Proc.new { |status, msg| puts status; puts msg }
)
analytics.track({
  user_id: "rohitpaulk@gmail.com",
  event: 'TEST',
  properties: {
    company_name: "company"
  }
})
analytics.flush
```

When using the correct write_key with the snippet, the request is successfully sent.

**Comment by f2prateek** [comment]
Yes this is expected. The tracking API behind api.segment.io is stateless and doesn't do any validation. It just pushes the messages onto a queue that can be processed separately. This allows the API to keep queueing messages even if an internal dependency (e.g. a database) is down for extended periods of time. This is similar to how the Google Analytics API works as well.
