### ISSUE TITLE
How do I pass custom options to Mailchimp?

### ISSUE THREAD

**Issue by yefim** [segmentio/analytics-ruby#140]
I'm reading through the docs for the Mailchimp integration and I can't figure out how to override the list ID in Ruby. The JS example is here: https://segment.com/docs/destinations/mailchimp/#overriding-list-id

So far I have:

``` ruby
SegmentClient.identify(
  user_id: 'abc123',
  traits: { email: 'abc123@gmail.com', firstName: 'Yefim', lastName: 'Ved' }
)
```

**Comment by f2prateek** [comment]
You can use the options or context field https://github.com/segmentio/analytics-ruby/blob/3c44ee9ffb7543c4779800e605877f10301266d7/lib/segment/analytics/client.rb#L82.

Something like:

```
SegmentClient.identify(
  user_id: 'abc123',
  traits: { email: 'abc123@gmail.com', firstName: 'Yefim', lastName: 'Ved' },
  context: { Mailchimp: { listId: "a list id" } }
)
```

For the future I'd recommend directing support questions to https://segment.com/contact - we generally have better monitoring for incoming requests there!
