### ISSUE TITLE
Should we be using /v1/batch instead of /v1/import? 

### ISSUE THREAD

**Issue by rohitpaulk** [segmentio/analytics-ruby#142]
This library currently [uses the `/v1/import` endpoint](https://github.com/segmentio/analytics-ruby/blob/master/lib/segment/analytics/defaults.rb#L7) to send events.

The other libraries [seem](https://github.com/segmentio/analytics-node/blob/bfe2d41bab70ba6045637f3cce3e0ec40506fece/index.js#L225) [to](https://github.com/segmentio/analytics-go/blob/bdb0aeca8a993b292b85c9ec17b5ce0ff81848c8/analytics.go#L302) be using `/v1/batch`, and I couldn't find docs for `/v1/import` at https://segment.com/docs/sources/server/http/#historical-import. Deprecated, maybe?

**Comment by f2prateek** [comment]
Yep, batch is recommended! Internally they're aliases but we're trying to consolidate and move to /batch.
