### ISSUE TITLE
When creating batches, limit by size in addition to number of items

### ISSUE THREAD

**Issue by rohitpaulk** [segmentio/analytics-ruby#144]
Split out from https://github.com/segmentio/analytics-ruby/issues/114#issuecomment-310813808. 

This will require a change to the public configuration API, as we currently support the `batch_size` parameter. 

![screen shot 2018-01-06 at 3 07 01 pm](https://user-images.githubusercontent.com/3893573/34638530-474d42b8-f2f3-11e7-917e-cfdb5288e04a.png)

**Comment by f2prateek** [comment]
It'd be nice to leave the existing API as is but mark it deprecated. I think the behaviour should be that batches are split into 500kb chunks or batch_size length batches, whichever comes first.

**Comment by rohitpaulk** [comment]
> I think the behaviour should be that batches are split into 500kb chunks or batch_size length batches, whichever comes first.

Makes sense. In that case, we can leave the configuration as is and amend the wording to mention that we'll also truncate by size if required.

**Comment by rohitpaulk** [comment]
PR ready for review: https://github.com/segmentio/analytics-ruby/pull/147

**Comment by rohitpaulk** [comment]
#147 is merged.
