### ISSUE TITLE
Does group support `anonymousId`?

### ISSUE THREAD

**Issue by rohitpaulk** [segmentio/analytics-ruby#146]
I noticed this when trying to use the ['common fields'](https://segment.com/docs/spec/common/) spec  to reduce code duplication in `client.rb`. 

In our code, it isn't passed on:

![screen shot 2018-01-08 at 9 50 00 pm](https://user-images.githubusercontent.com/3893573/34680294-ad0d022e-f4be-11e7-8439-0ac1556b3a66.png)

The docs say that it is allowed though: 

![screen shot 2018-01-08 at 9 48 45 pm](https://user-images.githubusercontent.com/3893573/34680317-bb30efdc-f4be-11e7-9cec-aa3269c20b2a.png)

**Comment by f2prateek** [comment]
Yes, `anonymousId` should be allowed in `group`. It's a very rare use case though and likely that very few customers have used it, likely why it wasn't noticed until now.
