### ISSUE TITLE
Anonymous id

### ISSUE THREAD

**Issue by sechix** [segmentio/analytics-ruby#173]
I don't know how to track users anonymous id , Now I am calling like this:
For user_id
                                        user_id: @user_id,
                                        event: 'Product Viewed',
                                        properties: {
                                            id: @product.id,
                                            sku: @product.sku,
                                            name: @product.name,
                                            price: @product.price,
                                            url: ['https://www.pislow.com/t/woman/', @product.slug].join('')
                                        }

for anonymous:
                                        event: 'Product Viewed',
                                        properties: {
                                            id: @product.id,
                                            sku: @product.sku,
                                            name: @product.name,
                                            price: @product.price,
                                            url: ['https://www.pislow.com/t/woman/', @product.slug].join('')
                                        }

And I get error in the second option that need a user_id or anonymous_id. But I don't know how put an id because documentation says that this gem create the anonymous_id.
What I have to send in anonymous users?

**Comment by f2prateek** [comment]
hey @sechix, please contact our support team https://segment.com/contact and they can help you out.

**Comment by sechix** [comment]
Sorry but I need your help, your colleagues in segment support are not able to solve my issue, even in several tickets during a lot of days. Bad support.
I need to know what I have to put in anonymous_id in track if the gem generates the id automatically and I don't know which is this id.
