### ISSUE TITLE
anonymous_id 

### ISSUE THREAD

**Issue by sechix** [segmentio/analytics-ruby#174]
I have a problem that segment support are not able to solve. I am using this gem, and to get the anonymous_id a use javascript 'analytics.user().anonymousId();'. the problem is that I send track event in controller and this script is executed in the view after. Is there some whay of get anonymous id un ruby with this gem?

**Comment by segmenttest** [comment]
hey @sechix, support questions similar to this are best routed to our support team: https://segment.com/contact.  

I see you already have an open thread with one of our Success Engineers on this concern.  

I'm closing this out in favor of that thread.

**Comment by TeresaNesteby** [comment]
hey @sechix, support questions similar to this are best routed to our support team: https://segment.com/contact.

I see you already have an open thread with one of our Success Engineers on this concern.

I'm closing this out in favor of that thread.

**Comment by sechix** [comment]
Sorry but nobody is answer my ticket  in support 2 days ago, even I have premium plan!

**Comment by TeresaNesteby** [comment]
@sechix Looks like you are trialing our Team plan.  That is our standard plan.  [You'll see in our pricing page](https://segment.com/pricing), our email response time for those on the standard plan is within[ 2 business days](https://cl.ly/d7c0756c78a3). 

We do not have support monitoring these repos. Our contact form is the most direct way to reach out to our team.

**Comment by sechix** [comment]
No, I am in the team plan where 120$/month

**Comment by leoplct** [comment]
+1 Interested. Any solutions?

**Comment by drewlustro** [comment]
+++

**Comment by nd4p90x** [comment]
Per Internal discussions:

This is consistent across all server side libraries. There is no way to actually get the anonymousId generated by the library. If I understand it correctly ( might be wrong please check ) the library generates an anonymousId per track call (?) …. but user can supply the anonymousId themselves, and do not (have to) rely on the one generated by the library.

"If the above understanding is correct, the developers can generate their own anonymousId, and do not (have to) rely on the library generated one. That way, they can then pass anonymousId to other parts of their application"

**Comment by drewlustro** [comment]
The problem we're seeing is chicken & egg. Given an anonymous user:

- `/login` page visit
  - Rails responds to request
    - no anonymousId cookie set, so generate one
    - include set-cookie header in response
  - ActionView renders haml of `/login` page, which includes `analytics.js`
    - `analytics.js` does not read the cookie set by Rails
    - `analytics.js` generates another UUID

A very narrow set of `track` events on the backend are attributed to the wrong anonymousId.

According to segment's own docs, we're not supposed to override `anonymousId` for anonymous traffic:

![Capture 2022-02-28 - 000017](https://user-images.githubusercontent.com/194885/156079919-012da20c-1ae5-45fc-a781-4490b7f28ea4.png)
