### ISSUE TITLE
The addition of commander as a dependency makes upgrading to 2.2.2+ difficult

### ISSUE THREAD

**Issue by petergoldstein** [segmentio/analytics-ruby#176]
We're locked on pre-2.2.2 versions of this gem (which are now quite old) because adding 'commander' as a dependency indirectly added a dependency on 'highline ~> 1.7.2'.  This is a very old version of 'highline' (circa 2015) and other libraries that depend on highline, like 'i18n-tasks' generally now require a highline version that is 2.0.0+

I'm not sure how big a piece of this gem the CLI is, but it's worth considering refactoring it to avoid a dependency on commander.

**Comment by f2prateek** [comment]
@rohitpaulk is there a way we can remove this from the library portion? we should only need commander for the cli

**Comment by rohitpaulk** [comment]
We're only using `commander` in the executable script used for CI. I've opened #177, which makes `commander` a development dependency instead of a runtime dependency.

**Comment by rohitpaulk** [comment]
I've also opened a PR to upgrade the version of `highline` that `commander` uses: https://github.com/commander-rb/commander/pull/73.

**Comment by f2prateek** [comment]
@petergoldstein can you give the changes on `master` a try?

**Comment by petergoldstein** [comment]
@f2prateek Yes, that unblocks the dependency issue.  Can you please package and release as a gem version?  That will allow me to update our production systems.

**Comment by lcpriest** [comment]
A further note on the commander -> highline dependency, `highline` uses an LGPL for their license, 
which is going to cause someone's lawyer to freak out that the LGPL appears in that gem.
