### ISSUE TITLE
Serialization error invalidates entire batch of events

### ISSUE THREAD

**Issue by tcollier** [segmentio/analytics-ruby#180]
I recently fixed an event tracking-related bug in my Rails app and while the fix was squarely in my app, I bumped into a few surprises with the `analytics-ruby` gem that I think offer opportunities for improvement. 

My bug was that a controller invoked `.track` with an event including a nested `ActionController::Parameters` property, which was not properly "permitted". The symptom of the bug was missing events in our downstream destinations. The fix was simple: call `.permit` on the parameters that go in the event payload.

The first surprise with `analytics-ruby` I encountered was that the `on_error` handler printed the error

```
Connection error: unable to convert unpermitted parameters to hash
```

The first part of the message (`"Connection error"`) incorrectly led me to believe that the issue was in establishing a connection with Segment servers. This nudged my investigation towards HTTP-related issues and I eventually opened up a support ticket with Segment. We eventually realized the issue was a serialization error and were then able to correctly identify the problem and fix it. Had the error been labeled `"Serialization error:`" or something similar, finding the root of the bug would've taken much less time.

The second surprise was that not only did we lose the events with an unserializable property (the "bad events"), but we also lost an order of magnitude more unrelated "good" events. Any good event in the same Rails process as a bad event had a chance of not making it to our destinations. My unsubstantiated hunch is that if a bad event is enqueued with a `.track` call, then all events in the batch (good or bad) will fail to make it to Segment servers.

Finally, while I was aware of the batching functionality of `analytics-ruby`, I was still surprised that the serialization error occurred asynchronously in the worker thread, rather than synchronously in the call to `.track`. The latter would've made it easier to detect and handle.

**Comment by rohitpaulk** [comment]
Thanks for the detailed issue, @tcollier. 

I agree that the "Connection error" is misleading, and that bad (serialization error) events shouldn't mess with good events. I'll attempt fixes for these soon.

Serializing on the main thread could impact performance and end up raising errors that might not really be critical (one bad segment event could crash your controller). Maybe a neater way to solve this could be to add a "DEBUG" mode that validates serialization on the main thread (only to be used in development/tests). @f2prateek do you know if we do anything similar in other client libraries?

**Comment by ajsharp** [comment]
I encountered similar issues, but with `BSON::ObjectId` objects instead of string ids. If I don't `to_s` my object ids, the event doesn't get sent, and nothing gets logged. @rohitpaulk Would you accept a pull request for a fix for this?

**Comment by rohitpaulk** [comment]
> If I don't to_s my object ids, the event doesn't get sent, and nothing gets logged

@ajsharp Do you have an `on_error` hook setup? If so, you should see these cases being logged. 

> @rohitpaulk Would you accept a pull request for a fix for this?

I'm not sure what you're proposing here - what fix do you have in mind? It is expected that objects that aren't JSON-serializable will cause errors.
