### ISSUE TITLE
Alias anonymous_id?

### ISSUE THREAD

**Issue by troex** [segmentio/analytics-ruby#181]
As per spec https://segment.com/docs/spec/alias/ it says that "Unique identifier for the user in your database. A userId or an anonymousId is required"

I'm exactly in situation when I know previous anonymous id and I know another (new) anonymous id - I know this is the same visitor but on another device, so I'd like to pass previous_id and anonymous_id but library says I need to specify user_id, but putting anonymous_id in user_id field could result in unexpected scenario.

Any suggestions?

**Comment by rohitpaulk** [comment]
You're right, according to the spec we must allow `anonymous_id` in `alias`. 

We're missing `anonymous_id` in `group` too - this is something we [noticed](https://github.com/segmentio/analytics-ruby/issues/146) a while ago, but hadn't gotten around to implementing.

Thanks for the report, @troex! I'll take a look at this soon.

**Comment by rohitpaulk** [comment]
Added this in #188. I'll cut a pre-release soon so that you can test it out, @troex. Will update here once done.

**Comment by troex** [comment]
latest `master` works for me with previous_id + anonymous_id scenario without user_id

**Comment by rohitpaulk** [comment]
Thanks for verifying, @troex! Pre-release PR opened in https://github.com/segmentio/analytics-ruby/pull/196.
