### ISSUE TITLE
Write key mandatory needed?

### ISSUE THREAD

**Issue by sluceno** [segmentio/analytics-ruby#182]
Hello

I am wondering why the `write_key` is mandatory for segment.

We are forced to set a key in development / testing / staging / pre_production while we are not going to push any metric whatsoever.

From my opinion the gem will be more usable without enforcing the `write_key`, we have for example the stub attribute which is really helpfull for those environments which we don't want to deactivate the tracking.

The Gem could run automagically in stub mode if no `write_key` is set.

There is probably a good reason to have it mandatory, please enlighten me if that's the case, I've been browsing in the Issues and could not find any related, so probably it's a misunderstanding from my side

Thanks! Keep up with the good work!

**Comment by rohitpaulk** [comment]
@sluceno Thanks for the report! I agree that checking for `write_key` doesn't make sense when stub mode is on. 

Two options we've got here: 

- Automatically run in stub mode if `write_key` isn't set
- Only check `write_key` if `stub` mode is off 

The latter is a non-breaking change and will force explicit usage of stub mode, so I'll go with that.

**Comment by f2prateek** [comment]
It doesn't seem that hard for clients to set a writeKey when using it in stub mode. You can even set it to something like `test`. Is this really needed?

**Comment by jhirn** [comment]
This makes for a frustrating but initial setup. It's not that hard to solve but it's not Rail'y.  ```ruby
SegmentAnalytics = Segment::Analytics.new({
    write_key: ENV['SEGMENT_API_KEY'] || "disabled",
    test: Rails.env.test?,
    stub: ENV['SEGMENT_API_KEY'] || Rails.env.development?,
    batch_size: 100,
    on_error: Proc.new do |status, msg|
      print status, msg
    end
})
```
