### ISSUE TITLE
.page() - ArgumentError: name must be given

### ISSUE THREAD

**Issue by troex** [segmentio/analytics-ruby#192]
Checking master branch to see if #181 is fixed gives me another error for `page` call `ArgumentError: name must be given`. I've been using this library prob since 2014 and I don't ever remember I needed to pass a name for a page call, the same as with JS library when I call `.page()` I don't need to specify "name", it's optional and I believe it should fallback to default "Loaded a Page"

**Comment by rohitpaulk** [comment]
Thanks for trying this out, @troex. 

This is indeed a behaviour change I noted in https://github.com/segmentio/analytics-ruby/pull/188:

>  This will result in the following behaviour changes:
> 
>  - alias will now accept anonymous_id
>  - group will now accept anonymous_id
>  - page will now validate that name is non-empty

Just verified against the spec, and `name` is indeed optional (ref: https://segment.com/docs/spec/page/). Will fix, nice catch!

**Comment by troex** [comment]
if I send empty page name or just no at all, with your latest change - will segment endpoint evaluate name to "Loaded a Page"?

**Comment by rohitpaulk** [comment]
@troex Yes, it will (as long as that was the behavior before).
