### ISSUE TITLE
Add possibility to pass options to Request initializer

### ISSUE THREAD

**Issue by troex** [segmentio/analytics-ruby#193]
This is feature request to be able to change/pass `Request` options like host, port and etc.

The reason why I'm asking for it - I'm working for a company which is Segment partner - "Attribution" and our new endpoints are segment spec compatible so we use `analytics` library to push events to our endpoint. Currently I have a workaround like:

```
module Segment
  class Analytics
    module Defaults
      module Request
        HOST = ENV['TRACKING_ENDPOINT']
        # PORT = 9292
        # RETRIES = 1
      end
    end
  end
end
```

+ We do a lot of historical imports and we also planning to become a "source" partner, so having an option not to drop events processing when `max_queue_size` is reached would be nice, currently have to workaround it like:

```
if @analytics.queued_messages >= @segment_max_queue_size - 1
  t = Time.now
  puts "Queue size #{@analytics.queued_messages}, flushing"
  @analytics.flush
  puts "Flush done in #{Time.now - t}, continue"
end
```

I know I could just fork project but these things looks reasonable to be standard features.

**Comment by rohitpaulk** [comment]
@troex Changing the host we push events to isn't a very common use case for us, I think the workaround you mentioned is easy enough to do. It also might be simpler to do if we access the constant directly without the nesting: 

```
Segment::Analytics::Defaults::Request::HOST = "yourhost.com"
```

**Comment by rohitpaulk** [comment]
Regarding `max_queue_size`, I'd suggest setting it to an extremely high number as a workaround. Any violations can also be caught by checking the return value of `analytics.flush` (`True` if the event was queued, `False` if the queue was full)

**Comment by troex** [comment]
thanks for the suggestion - the problem with "extremely high number" is OOM, recently processed 50 Gb of data in one run, our data been coming from DB cluster really fast so had to throttle using described method above.

I kind of agree that our use case is probably not very typical just was thinking mostly of ideas from open-source version of analytics.js where you can skip sending events to segment and send events to integration endpoints.
