### ISSUE TITLE
Events not sending with Puma

### ISSUE THREAD

**Issue by phildionne** [segmentio/analytics-ruby#195]
I'm having trouble sending events in production with a Puma server. This problem has been raised in https://github.com/segmentio/analytics-ruby/issues/37 but the solution outlined there doesn't seem to work anymore.

My understanding of the desired behavior here is that we'd want a global `$AnalyticsBackend` instance that is shared across threads, in order to benefit from the batching mechanism.

Any idea of where to dig further?

Configuration:
- Rails 5.2.2
- Ruby 2.5.3
- Puma 3.12.0

```ruby
class Analytics
  class_attribute :backend, instance_writer: false, default: $AnalyticsBackend

  def track(event:, properties: {})
    # ...
  end

  # ...
end
```

```ruby
# initializers/analytics.rb

$AnalyticsBackend = Segment::Analytics.new({
  write_key: "...",
  on_error: Proc.new { |status, msg| print msg }
})
```

```ruby
# config/puma.rb

threads 5, 5

workers 2

on_worker_shutdown do
  Analytics.flush
end

preload_app!

# ...
```

**Comment by rohitpaulk** [comment]
@phildionne What symptoms are you seeing here? Do no events get sent at all, or do some get through? Also, what version of the gem are you using? Do you see any logs printed out? 

I'll also take a look at Puma's docs soon and come up with a recommended configuration. 

(Sorry for the late reply, I seemed to have accidentally marked this as read in my notifications!)

**Comment by phildionne** [comment]
@rohitpaulk no worries! Thanks for following up.

> What symptoms are you seeing here?
In development events are reaching Segment, but not in production.

> what version of the gem are you using?
2.2.5

> Do you see any logs printed out?
If you are referring to `on_error: Proc.new { |status, msg| print msg }` I'm not sure what to grep for. Is there a specific pattern I could search for?

Also, I'm now pretty sure that I shouldn't instantiate a global variable in a rails initializer, per https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-initializers

I will now get rid of the initializer + global approach and use a singleton instead. Will follow up with results soon.

**Comment by rohitpaulk** [comment]
Thanks for the update, @phildionne. 

> If you are referring to on_error: Proc.new { |status, msg| print msg } I'm not sure what to grep for. Is there a specific pattern I could search for?

Yes, we prefix all logs with `[analytics-ruby]`. [ref](https://github.com/segmentio/analytics-ruby/blob/244e1adf40e1936c7bc475c17400fc2b9e619009/lib/segment/analytics/logging.rb#L41). 

> Also, I'm now pretty sure that I shouldn't instantiate a global variable in a rails initializer, per https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-initializers

> I will now get rid of the initializer + global approach and use a singleton instead. Will follow up with results soon.

Nice! Do let us know how this goes - we could add your configuration as a note to our documentation.

> 2.2.5

Not sure if this is what you're running into, but there was a bug in 2.2.5 that caused partial loss of events if you had both `rails` and `oj` installed. Details [here](https://github.com/segmentio/analytics-ruby/issues/161). I'd recommend upgrading to 2.2.7 so that we can rule out bugs that were fixed in the past :slightly_smiling_face:

**Comment by phildionne** [comment]
I've finally solved this issue by refactoring the implementation, making the behavior more explicit with `Singleton` and removing instantiation from `initializers`. It now works according to expectations, therefore I suspect this wasn't related to Puma.

Sharing the result here:

```ruby
# config/puma.rb

threads 5, 5

workers 2

on_worker_shutdown do
  Analytics.flush
end

preload_app!

# ...
```

```ruby
class Analytics
  class Backend
    include Singleton

    attr_reader :service
    private :service

    # @see https://segment.com/docs/sources/server/ruby
    delegate :flush, :identify, :track, :alias, :group, :page, to: :service

    # @return [Segment::Analytics]
    def initialize
      @service = Segment::Analytics.new({
        write_key: "...",
        on_error: Proc.new { |status, message| Segment::Analytics.logger.error(message) }
      })
    end
  end
end
```

```ruby
class Analytics
  cattr_accessor :backend, instance_writer: false

  attr_reader :user

  # @param user [User]
  def initialize(user)
    @user = user
  end

  # @param event [String]
  # @param properties [Hash, Nil]
  # @return [Analytics]
  def track(event:, properties: {})
    tap do
      backend.track(user_id: user.id, event: event, properties: properties)
    end
  end

  # @return [Analytics]
  def identify
    tap do
      backend.identify(user_id: user.id, traits: {
        email: user.email,
        ...
      })
    end
  end

  # @return [Nil]
  def self.flush
    backend.flush
  end
end

Analytics.backend = Analytics::Backend.instance
```

@rohitpaulk  thanks for helping out!
