### ISSUE TITLE
Add a has_many association array 

### ISSUE THREAD

**Issue by masudhossain** [segmentio/analytics-ruby#204]
I can track a user completely fine, but i also would like to track the projects that person has done. 

Is there a way to do this? 

I tried doing the following, but it will result in a syntax error. 

```
analytics.identify(
      user_id: 42,
      traits: {
        email: 'name@example.com',
        first_name: 'Foo',
        last_name: 'Bar'
        Project.all.each do |project|
          project: "project_#{project.id}",
        end
     }
   )
```

**Comment by rohitpaulk** [comment]
Hi @masudhossain. As you mentioned, the above would result in a syntax error. I'd suggest sending an array (`["project_1", "project_2"]`) instead - 

```ruby
{
  email: "name@example.com",
  projects: [Project.all.map { |project| "project_#{project.id}" }]
}
```
