### ISSUE TITLE
Too many requests : Failed after 10 retries/Too many sockets opened

### ISSUE THREAD

**Issue by tdutreui** [segmentio/analytics-ruby#207]
Hi,

I'm writing a script calling "identify" for about 10k users.
Most of the API calls fail because there are too many sockets opened. A lot of them also fail after 10 retries.
Debugging (by reading development.log), I found that a request is made for each call to the "identify" method, which explains the failures.
I'm using analytics-ruby (2.2.7)

My current workaround is :
```
  User.all.find_in_batches(batch_size: 100) {|users_slice|
    users_slice.each {|user| Tracker.track_user user}
    Tracker.flush
    sleep 10
  }
```

What about a "min_batch_size" option to avoid this problem ?
Thank you
Thomas

**Comment by rohitpaulk** [comment]
Thanks for the report @tdutreui. Could you share the debug logs you're seeing? The current batching mechanism _should_ have worked here - it doesn't open more than one connection per thread. 

As an example, here's a sample script and it's output: 

```ruby
require "analytics-ruby"

analytics = Segment::Analytics.new(write_key: 'xxxxx')

(1..10000).to_a.each { |i|
  puts "tracking #{i}"
  analytics.identify(
    user_id: 42,
    traits: {
      test: "test#{i}"
    }
  )
}

analytics.flush
```

```
tracking 1
tracking 2

...

tracking 9998
tracking 9999
tracking 10000
D, [2019-09-26T22:28:05.355252 #7642] DEBUG -- Segment::Analytics: [analytics-ruby] Response status code: 200
D, [2019-09-26T22:28:05.358313 #7642] DEBUG -- Segment::Analytics: [analytics-ruby] Sending request for 100 items
D, [2019-09-26T22:28:07.428471 #7642] DEBUG -- Segment::Analytics: [analytics-ruby] Response status code: 200
D, [2019-09-26T22:28:07.431682 #7642] DEBUG -- Segment::Analytics: [analytics-ruby] Sending request for 100 items

...
```

**Comment by tdutreui** [comment]
Hi,
I'm sorry, it was just en error in my implementation.
Everything is working fine indeed, thank you for your answer @rohitpaulk and big up for this lib :)
