### ISSUE TITLE
Incorrect event category on Google Analytics 

### ISSUE THREAD

**Issue by tamtran-agilityio** [segmentio/analytics-ruby#208]
When I send an event from Segment to Google Analytics value on the event category is `All`. The value is not the same as the library `analytics.js` is EnhancedEcommerce. You can help me? Thanks!

**Comment by rohitpaulk** [comment]
@tamtran-agilityio The usage is slightly different for Ruby vs Javascript. 

Screenshots from documentation attached: 

[docs link](https://segment.com/docs/destinations/google-analytics/#enhanced-e-commerce)

**Javascript**:

![2019-10-06-040631_852x224_scrot](https://user-images.githubusercontent.com/3893573/66261634-cb446280-e7ee-11e9-8934-8f5991aeba39.png)

**Ruby**: 

![2019-10-06-040623_847x292_scrot](https://user-images.githubusercontent.com/3893573/66261635-ced7e980-e7ee-11e9-88dd-d86a98c0f3a3.png)
