### ISSUE TITLE
Use sorbet to type check code

### ISSUE THREAD

**Issue by bsneed** [segmentio/analytics-ruby#218]
A type checker makes it easier to catch errors in our code. It adds the guardrails so we have more confidence and can move faster.
https://sorbet.org

Unclear if this will add any weight to the library we publish, or if it can be used solely in an internal components.

Once adopted internally, we might be able to add type hints to the Ruby library public API as well.

**Comment by bsneed** [comment]
To be clear, this was a ticket on our internal JIRA.  Just passing it here for any feedback that might exist.

**Comment by nd4p90x** [comment]
I am all for adding this into the LIB, we will also need to incorporate it into the CI tests after we convert to CircleCI as well.  I would recommend a new branch for incorporation and to determine if it will cause us to refactor a large portion of the code.  I am open for other suggestions as well.
