### ISSUE TITLE
Problem when using a default timestamp

### ISSUE THREAD

**Issue by floriank** [segmentio/analytics-ruby#219]
Hey,

we're using Segment quite extensively and have noticed a small problem when leaving the `timestamp` empty. 

Example call:

```ruby
analytics = Segment::Analytics.new(write_key: "<my_write_key>")

analytics.track(
  user_id: SecureRandom.uuid, 
  event: "something_interesting_happened", 
  properties: {
    foo: "bar"
  }, 
  context: {
    version: 2
  }
)
```

The call goes through nicely, and the event information gets stored with Segment. Here is an example of a raw event landing in the debugger:

```javascript
{
  "context": {
    "library": {
      "name": "analytics-ruby",
      "version": "2.2.8"
    },
    "protocols": {
      "sourceId": "UOuOeVQwLs"
    }
  },
  "event": "something_interesting_happened",
  "integrations": {},
  "messageId": "b7a8ab68-bae4-4be6-837d-8d9b2dd206c6",
  "originalTimestamp": "2020-04-17T10:22:17.457+00:00",
  "properties": {
     "foo": "bar"
  },
  "receivedAt": "2020-04-17T10:22:17.735Z",
  "sentAt": "2020-04-17T10:22:17.458Z",
  "timestamp": "2020-04-17T10:22:17.734Z",
  "type": "track",
  "userId": "a036f91a-c60c-489b-9025-1781ef3b3b0d",
  "writeKey": "<my_write_key>"
}
```

The problem comes for us downstream, as the `originalTimestamp` is malformed (It's missing the `Z`). We currently send the data to an AWS destination, which cannot handle this timestamp format and breaks subsequently. 

Looking at the other timestamps, this might be an oversight/inconsistency.

I tracked the problem down to https://github.com/segmentio/analytics-ruby/blob/master/lib/segment/analytics/utils.rb#L67.

If i call that function with the [default for timestamp](https://github.com/segmentio/analytics-ruby/blob/master/lib/segment/analytics/field_parser.rb#L137):

```ruby
time_in_iso8601(Time.new)
#=> "2020-04-17T09:58:39.239+00:00"
```

Please advise if this is intended behaviour.

**Comment by rohitpaulk** [comment]
Thanks for the detailed report, @floriank - I'll take a look at this soon.

**Comment by floriank** [comment]
Thanks for checking it out, if you need any further information, let me know.

**Comment by rohitpaulk** [comment]
I can confirm that this value is indeed sent by the Ruby library. The other timestamps are calculated by Segment and automatically appended ([details here](https://segment.com/docs/connections/spec/common/#timestamp-overview)).

According to the iso-8601 spec, both timestamps _should be_ equivalent. [ref](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators)

> An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00". However, it is not permitted to state it numerically with a negative sign, as "−00:00", "−0000", or "−00". The section dictating sign usage (section 3.4.2 in the 2004 edition of the standard) states that a plus sign must be used for a positive or zero value, and a minus sign for a negative value.

I checked how a few languages handle this, here are the results: 

Ruby (uses `+00:00`) 

```
➜  irb
irb(main):001:0> require "date"
=> true
irb(main):002:0> DateTime.now.new_offset(0).iso8601
=> "2020-04-20T09:44:41+00:00"
```

Python (uses `+00:00`)

```
➜ python
Python 3.8.2 (default, Apr 17 2020, 18:30:09) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dateutil.tz import tzutc
>>> from datetime import datetime
>>> datetime.utcnow().replace(tzinfo=tzutc()).isoformat()
'2020-04-20T09:46:41.950964+00:00'
```

NodeJS (uses `Z`) 

```
➜  node
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> (new Date()).toISOString()
'2020-04-20T09:53:47.010Z'
```

Python and Ruby both use the offset format (`+00:00`), but node uses the special `Z` format. 

I don't see a problem in sticking to `Z` if it is more widely compatible, as long as it is straightforward to implement. This might be a widespread problem that we'll have to check & fix across all of our libraries. 

I'd like to understand this problem a bit more before proceeding with a fix. @floriank could you tell me what AWS destination you're seeing this problem with?

**Comment by floriank** [comment]
I cannot give you too much insights as I am the engineer working on sending event to segment.

I have to summon the awesome powers of @snowbeta here to give more insights about what happens next!

**Comment by snowbeta** [comment]
Hi @rohitpaulk ,

Thanks for the information here, 

To speak more about our use case, we use Kinesis Firehose for the conversion of JSON into Parquet which uses OpenXJson Serializer as shown in this [link](https://docs.aws.amazon.com/firehose/latest/dev/record-format-conversion.html#record-format-conversion-deserializers). 

Currently, we are only using 3 SDKs:

1. Go
2. JavaScript
3. Ruby

As you mentioned, Javascript does use `Z` in their timestamp.
It also happens that Go SDK will provide something like this -> `2020-04-20T13:58:11.386809579Z`
with the inclusion of `Z`.

I cannot speak for Python, but if it did not include `Z` it would have likely failed for our use case.

**Comment by rohitpaulk** [comment]
Thanks for the info @snowbeta & @floriank. 

I looked into whether we can force using `Z`, but turns out it isn't straightforward - will require re-implementing the standard library functions in many cases (unless the programming language does it by default). 

Given that the current implementation adheres to ISO-8601 and hence satisfies the [Segment spec](https://segment.com/docs/connections/spec/common/#timestamps), I don't think the trade-off is worth it.  

I'm not sure what a good workaround looks like here, but you could either transform the format on your end, or probably drop the `originalTimestamp` column and rely on `timestamp` (which tends to be more accurate, and happens to match the format you need).

**Comment by floriank** [comment]
Just for completeness:

We currently enforce passing a timestamp with every segment call and documented the issue internally. Works for us, but in case Segment runs into similar issues with other customers, this might be a useful thing to document for the integration of destinations.

Thanks for looking into it!
