### ISSUE TITLE
Supress logger

### ISSUE THREAD

**Issue by jewilmeer** [segmentio/analytics-ruby#220]
Hi!

We recently started using this gem to send our data to Segment. Within our test suite we choose to use the `stub: true` option for the client, which produces a lot of output, which is cluttering our logs.

Is there a way to disable / redirect this logging?

**Comment by ojab** [comment]
`Segment::Analytics::Logging.logger = Logger.new(nil)` or whatever logger you want.

**Comment by nd4p90x** [comment]
If there are further concerns or issues related to this, please feel free to re-open.  Thank you.
