### ISSUE TITLE
2.2.8 version stopped sending category on page view tracking

### ISSUE THREAD

**Issue by fabriciopapa** [segmentio/analytics-ruby#221]
Is there a reason why `category` stopped from being sent in that version?

The segment client still accepts that parameter:
https://segment.com/docs/connections/sources/catalog/libraries/server/ruby

In addition, `segment/analytics/field_parser.rb:parse_for_screen` still accepts `category`, why don't do the same for `parse_for_page`?

Thank you in advance.

**Comment by nd4p90x** [comment]
I do see the category field in the documentation, however, I don't see where it was ever part of the Page method in code.  I will confirm that the docs are accurate and if so, I will add the field to the page method.  Thank you.
