### ISSUE TITLE
Convert from Travis CI to CircleCI

### ISSUE THREAD

**Issue by nd4p90x** [segmentio/analytics-ruby#228]

**Comment by ryanwjackson** [comment]
@nd4p90x FYI: we just made the switch to Github Actions for our testing and deployment of LedgerSync (an open-source ERP connector). This is our current version: https://github.com/LedgerSync/ledger_sync-template_ledger/blob/master/.github/workflows/gem-workflow.yaml

**Comment by nd4p90x** [comment]
This is being place on hold at the moment.  I setup the circleci tests and rubygems deployment, however, there are a few hiccups and since Travis ci does work, we will consider changing this once the need is greater in the future.
