### ISSUE TITLE
Enable Logging

### ISSUE THREAD

**Issue by spencerattick** [segmentio/analytics-ruby#231]
Hey folks! It looks like this library [includes logging](https://github.com/segmentio/analytics-ruby/blob/5202c1d1edf7ddeade0b9e839016b7ed6bfcee4e/lib/segment/analytics/logging.rb) however I have been unable to get it up and running. Would you all be able to provide an example? I can add this to Segment's public documentation as well so that it's something everyone is aware of. Thanks!

**Comment by nd4p90x** [comment]
@spencerattick Thank you for your question, here is a quick implementation describing adding a debug message to your logged output using the log wrapper:

```
myLog = analytics.logger

myLog.debug("User Create Account Logged")
```

This Generates the following output:

_D, [2021-05-29T10:39:10.156734 #79289] DEBUG -- Segment::Analytics: [analytics-ruby] User Create Account Logged_

I hope this answers your question, if not, please feel free to re-open the issue and we can discuss further.
