### ISSUE TITLE
at_exit question

### ISSUE THREAD

**Issue by spencerattick** [segmentio/analytics-ruby#233]
Hey folks! A Segment customer I'm speaking to is pretty concerned that analytics-ruby could shut down unexpectedly (power outage for the customer, connectivity issues, etc.) and then their data would either be lost or would be sent again on retry (to create duplicates). The customer found a method called at_exit that they think will help them flush the queue before an outage. We've seen that Segment uses that method in the analytics-ruby library ([link to line in code](https://github.com/segmentio/analytics-ruby/blob/5202c1d1edf7ddeade0b9e839016b7ed6bfcee4e/lib/segment/analytics/client.rb#L33)). Can anyone confirm that's what's happening? Thanks!

**Comment by nd4p90x** [comment]
@spencerattick Thank you for your question.  If a proper exit can be attained, then this process would ensure that the worker_thread is exited and any function of the exit be performed at that time, flushing, cleanup, etc.  However, if there is a system failure that does not allow a proper exit of the program, unless the user is queuing the messages in a file or database, then the data would be lost.
