### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by gonzar11** [segmentio/analytics-ruby#234]
Hey, I am seeing that in the doc we have the :stub option but as I see in the codebase is no longer available.
Thanks!

**Comment by nd4p90x** [comment]
@gonzar11 can you direct me to the location of the issue in the docs?  Thank you.

**Comment by gonzar11** [comment]
Yes sure:
_You can use the stub: true option to Segment::Analytics.new to cause all requests to be stubbed, making it easier to test with this library._
