### ISSUE TITLE
Adding message_id to track call using js2.0 style messageId fails to process

### ISSUE THREAD

**Issue by nicholasluimy** [segmentio/analytics-ruby#241]
When calling track with a `message_id` following the format in the upgraded 2.0 library (E.g `ajs-next-bebb1042be1ef84fa0af0ca5fcb286cc`), there is a 200 response but the message is never received in segment app

Log shows:
```
[analytics-ruby] Sending request for 2 items
[analytics-ruby] Response status code: 200
```

Further testing to isolate issue:
- string parsing issue, but it works with a message_id of `...`
- string length issue, but it works with a message_id of `ajs......bebb1042be1ef84fa0af0ca5fcb286cc`
- string blacklist issue, but it works with `-next-`

**Comment by nicholasluimy** [comment]
Had a debug section with a CSX rep - seems like it's Segment's internal dedupe logic causing the message to not be received 

https://segment.com/docs/guides/duplicate-data/

It was not obvious that deduplication happens across different event sources (in our case, it was deduping between events across different sources, where we introduced behavior to explicitly duplicate events)

**Comment by nd4p90x** [comment]
Thank you for following up with your issue.  That was going to be the first thing I checked.  Let us know if we can help you with anything else.
