### ISSUE TITLE
Using `Analytics.flush` to ensure event delivery order?

### ISSUE THREAD

**Issue by jurvis** [segmentio/analytics-ruby#242]
Hello there, we have a bunch of analytics call we do upon user sign up which looks something like this:

```
    # user created somewhere above

    Analytics.identify(
      user_id: user.id,
      traits: {
        email: user.email,
        ...
      }
    )

    Analytics.flush

    Analytics.track(
      user_id: user.id,
      event: "User Sign Up",
      properties: analytics_properties
    )

    Analytics.track(
      user_id: user.id,
      event: "Subscription Created",
      properties: analytics_properties
    )
```

We want to specifically ensure that `Analytics.identify` is called before any of the other two `Analytics.track` events.

However, it does seem like `Analytics.flush` may not be the right tool for ensuring delivery order since we see some of the track events arrive at Customer.io before identify. Do you have any suggestions on what the best approach is for what we are trying to achieve?

Thanks!

**Comment by pooyaj** [comment]
Hi @jurvis, Segment pipeline does not guarantee the order of the delivery unfortunately. While there is no exact science here, but usually if the events are spaced enough ( maybe sending track calls with a second of delay ) you should be getting consistent results.

**Comment by jurvis** [comment]
got it -- thank you! just making sure there wasn't a best practice I missed :)

**Comment by tothpeter** [comment]
@pooyaj Does the identify call have to arrive before the track event? Couldn't we just add all the necessary properties like email name etc to the track event so the whole behavior won't depend on the order?

**Comment by tothpeter** [comment]
Segment support told me that the order doesn't matter. I've just realized that it does for Klaviyo. The identify call has to go before any event. And the ID call has to provide all the basic details.

**Comment by tothpeter** [comment]
Segment support told me that the order doesn't matter. For the Klaviyo integration it is fine unless you tie something to the event, like sending en email or something. Although it seems if you specify the email in the properties of a track event, Klaviyo will associate it with a user even if the identify call arrives later.
