### ISSUE TITLE
window._cio.page is not a function

### ISSUE THREAD

**Issue by andresespinosapc** [segmentio/analytics-ruby#244]
I'm constantly getting this error when using Customer.io integration: https://sentry.io/share/issue/786a3ed56d9b4d4aa95d4969d0d8972f/

The integration works fine though, I haven't found any problem yet.

**Comment by pooyaj** [comment]
Hi @andresespinosapc! This is related to our Javascript library, instead of Ruby. Could you please point me to the live website where I can reproduce the issue?

**Comment by pooyaj** [comment]
Please feel free to re-open if this is still an issue.
