### ISSUE TITLE
override listid for mailchimp

### ISSUE THREAD

**Issue by jamesascarter** [segmentio/analytics-ruby#246]
Hiya. 

I did find this as a closed issue: https://github.com/segmentio/analytics-ruby/issues/140.

But this approach does not seem to work for me. Is this still supported? It seems that this gem does not accept context.

I would like to send up a specific ListId for Mailchimp to override the default.

Thanks

**Comment by jamesascarter** [comment]
so i can now see that the gem does send `context: { Mailchimp: { listId: 'xxxxxxxxx' } }` in payload. BUt can not see this in the segment debugger. SO it seems to be filtered out somewhere?

**Comment by nd4p90x** [comment]
@jamesascarter If this continues to be an issue for you, feel free to re-open.  Thank you.
