### ISSUE TITLE
Missing some tracked events in debugger

### ISSUE THREAD

**Issue by gabe-wilber-careport** [segmentio/analytics-ruby#255]
I have a situation where I run 4 sequential API calls with `RestClient::Request` and in between each call I am using `.track` to send information about the API responses to Segment.

The issue I am having is about 5% of the events I am tracking are not showing up in the Segment debugger. I know it is not an issue with the API calls I am making as I am logging the responses to the console and will rerun the same exact calls back to back and most times all 4 events are tracked in Segment, but sometimes only 3 or even 2 show up.

**Comment by nd4p90x** [comment]
@gabe-wilber-careport sorry for any confusion, however, this is by design.  Within the docs it explains this occurring and why:  https://segment.com/docs/connections/sources/debugger/
Thank you

**Comment by gabe-wilber-careport** [comment]
@nd4p90x thank you for the quick response. This clears things up for me.
