### ISSUE TITLE
::Segment is too generic a namespace

### ISSUE THREAD

**Issue by iain-bryson** [segmentio/analytics-ruby#256]
Hello,

We have a product with its own concept of `Segment` unrelated to Segment-the-service. In order to use this gem we've had to fork and rename `::Segment` to `::SegmentIO`. Would you consider making this change, or accepting a PR for the change?

**Comment by nd4p90x** [comment]
@iain-bryson Please submit a PR, we will review the request and get back to you.  Thanks!
