### ISSUE TITLE
API returns a 200 with wrong auth key

### ISSUE THREAD

**Issue by spuyet** [segmentio/analytics-ruby#257]
Hey,

I was checking if our error monitoring tool could be notified if we had wrong credentials for the Segment API and it looks like the API still returns a 200 with any credentials, here is an example:

```
irb(main):001:0> require 'analytics-ruby'
=> true
irb(main):002:0>
irb(main):003:1* client = Segment::Analytics.new(
irb(main):004:1*   write_key: 'yolo',
irb(main):005:2*   on_error: Proc.new do |status, msg|
irb(main):006:2*     print msg
irb(main):007:1*   end
irb(main):008:0> )
=>
#<Segment::Analytics:0x0000000104f128b8
...
irb(main):009:0>
irb(main):010:1* client.track(
irb(main):011:1*   user_id: 42,
irb(main):012:1*   event: 'baz',
irb(main):013:1*   properties: { foo: 'bar' }
irb(main):014:0> )
=> true
D, [2022-12-19T18:23:24.761804 #59424] DEBUG -- Segment::Analytics: [analytics-ruby] Sending request for 1 items
irb(main):015:0> D, [2022-12-19T18:23:25.557777 #59424] DEBUG -- Segment::Analytics: [analytics-ruby] Response status code: 200
```

To reproduce:
```ruby
require 'analytics-ruby'

client = Segment::Analytics.new(
  write_key: 'yolo',
  on_error: Proc.new do |status, msg|
    print msg
  end
)

client.track(
  user_id: 42,
  event: 'baz',
  properties: { foo: 'bar' }
)
```
Shouldn't we receive a 401 for this kind of case ? See errors documentation: https://segment.com/docs/connections/integration_error_codes/

**Comment by nd4p90x** [comment]
Thank you for posting this issue, we will begin looking into this soon.

**Comment by spuyet** [comment]
@nd4p90x up !

**Comment by MichaelGHSeg** [comment]
Apologies for how long it took to respond to this, but the error codes in that document don't refer to the tracking API.  You can find information about tracking API errors here: https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#errors

**Comment by spuyet** [comment]
Hmm it does not make sense to respond a 200 when there is issue with auth/invalid data or whatever, how can we know if there is any issue coming from our side ? You should think about better error management, people will probably lose lot of data because of this anti-pattern.

**Comment by felipefava** [comment]
I had the same problem haha, I agree that shouldn't be the expected behaviour, it's not very intuitive...
