### ISSUE TITLE
Nil error message in Segment::Analytics::Response object

### ISSUE THREAD

**Issue by elias19r** [segmentio/analytics-ruby#270]
Hi!

I noticed that this [`JSON.parse(body)` in `Segment::Transport#send`](https://github.com/segmentio/analytics-ruby/blob/2.4.0/lib/segment/analytics/transport.rb#L43) doesn't have an `"error"` key when the response status code is 400, which causes the returned `Response` object to be created with a `nil` error message because `JSON.parse(body)['error']` is `nil`.

This is the snippet I used in a Rails app console to verify that:

```rb
# Gemfile

gem "analytics-ruby", "~> 2.4.0", require: "segment/analytics"
```

```rb
# bundle exec rails console

client = Segment::Analytics.new(
  test: true,
  write_key: "",
  on_error: Proc.new do |status, error|
    puts ">>>>> status=#{status.inspect}"
    puts ">>>>> error=#{error.inspect}"
  end
)

client.track(anonymous_id: 'test', event: 'test', properties: {})
```

Output:

```
[analytics-ruby] Sending request for 1 items
[analytics-ruby] {
  "success": false,
  "message": "An invalid write key was provided",
  "code": "invalid_request"
}
[analytics-ruby] Response status code: 400
>>>>> status=400
>>>>> error=nil
```

The only keys present in the JSON response are `"success"`, `"message"`, and `"code"`.

**Comment by nd4p90x** [comment]
@elias19r thank you for your report.

We will begin look into this

**Comment by nd4p90x** [comment]
After review of this issue, we have determined that the response from the server is adequate to determine the cause of the failure.

Thank you for your inquiry
