### ISSUE TITLE
Catching "Exception" is problematic

### ISSUE THREAD

**Issue by soma** [segmentio/analytics-ruby#72]
Hello,

We were integrating your ruby client today, and tried to mock it using VCR. But since all Exceptions are swallowed in your client, this did not work.

See here: https://github.com/segmentio/analytics-ruby/blob/master/lib/segment/analytics/request.rb#L58

This line catches "Exception", which is really bad form. (You will be stabbed by Zenspider: http://www.zenspider.com/Languages/Ruby/QuickRef.html#general-tips)

For more info, see here: http://daniel.fone.net.nz/blog/2013/05/28/why-you-should-never-rescue-exception-in-ruby/

And there is a lot of other resources discussing this topic.

So what to do instead? See here: http://stackoverflow.com/questions/5370697/what-s-the-best-way-to-handle-exceptions-from-nethttp

Among the responses is a lib from us: https://github.com/barsoom/net_http_timeout_errors (but it probably does not catch everything you might want to catch)

We ended up stubbing the client using your :stub instead of using VCR, but I really, really think you should reconsider your exception handling.

**Comment by f2prateek** [comment]
I agree, sorry for the delay, tracking internally https://segment.atlassian.net/browse/LIB-112
