### ISSUE TITLE
Multiple retries skewing metrics.

### ISSUE THREAD

**Issue by vincentpaca** [segmentio/analytics-ruby#73]
We're using Segment to funnel data into Mixpanel. Recently, we've updated to `2.0.11` from `2.0.6`.

After the gem upgrade, the number of events to Mixpanel has increased dramatically. Normally, we send around 5k events per day, after we upgraded it shot up to **5m (million)** events being sent.

Looking at the changelog, it looks like retries have been added to the later versions. I'm not 100% sure that this is what is causing the huge data spikes that we are experiencing but it most likely is. We don't have any retry logic when sending events, and we didn't change any logic on our end together with the gem upgrade.

We're still investigating this issue but I'm wondering if this could be the case. We've downgraded back to `2.0.6` for now and it seemed to have gone back to normal.

**Comment by travisjeffery** [comment]
@vincentpaca Hey Vincent, thanks for the issue. I just pushed a release that should fix the amount of duplicates you're seeing. Can you check that and let me know that it works for you?

**Comment by vincentpaca** [comment]
Hey @travisjeffery , thanks for the fix. Would be very interested to know about the actual issue and how it happened.
