### ISSUE TITLE
Executing segment client from a rake task fails

### ISSUE THREAD

**Issue by ryannealmes** [segmentio/analytics-ruby#77]
Segment has been working like a charm for us, but I have recently run into the problem below.

When I run any segment tracking via a rake task it just doesn't send the event. It doesn't report any errors either. If I run this same code in my rails console it works perfectly and comes through on the debugger.

Segment::Analytics.new({write_key: "mykey"}).track(user_id: "email@address.co.za", event: "test event", properties: {code: "hello"})

Is there some limitation that I need to be aware of?

Thanks.

**Comment by ryannealmes** [comment]
So after some more investigation, I have managed to replicate the problem with minimal code. If you strip out the request from the analytics library it seems when you run the code in a separate thread it doesn't work.

Example below for rake file
```
require 'segment'
namespace :segment do
  task :test_me  do
    Thread.new do
      puts 'start'
      options = {:host=>"api.segment.io", :port=>443, :ssl=>true, :headers=>{:accept=>"application/json"}}
      http = Net::HTTP.new(options[:host], options[:port])
      http.use_ssl = options[:ssl]
      http.read_timeout = 8
      http.open_timeout = 4
      request = Net::HTTP::Post.new("/v1/import", {"Content-Type"=>"application/json", "accept"=>"application/json"})
      request.basic_auth "mykey", nil
      res = http.request(request, '{"sentAt":"2015-03-08T16:47:33.607+02:00","batch":[{"event":"test event","userId":"email@address.co.za","anonymousId":null,"context":{"library":{"name":"analytics-ruby","version":"2.0.12"}},"options":null,"integrations":null,"properties":{"code":"hello"},"timestamp":"2015-03-08T16:47:33.607+02:00","type":"track","messageId":"0c500a0c-12b3-482b-ad74-ddd95a26b221"}]}')
      puts 'end'
    end
  end
end
```

I am not really the greatest with threads, but from the example above it seems like the thread fires since it prints out start, but it doesn't reach the end statement.

Any ideas? I will keep investigating, but this is really becoming an issue for us :/

**Comment by ryannealmes** [comment]
I have managed to figure out the exact [issue](http://stackoverflow.com/questions/28928560/why-does-http-request-fail-when-running-from-rake-task-in-a-thread) here.

It seems that when you make an http request in a thread that is run via a rake task, it fails. It can be fixed by getting the value of the thread.

```
thread = Thread.new do
.
.
.
end
thread.value
```
Really weird  ... and not really a solution.

**Comment by ryannealmes** [comment]
After more investigation I see this library has a flush method which resolves this issue all together. And I see that the [docs] (https://segment.com/docs/libraries/ruby/) say I should flush if writing a script.

A few hours later ... 

A great conversation with myself :)

**Comment by jsiragusa** [comment]
@ryannealmes FWIW, I was running into the same situation and this issue helped.  So thanks for that conversation with yourself. :)
