### ISSUE TITLE
'.name must be a string'  on page call

### ISSUE THREAD

**Issue by raysrashmi** [segmentio/analytics-ruby#80]
For page tracking we are calling  

arguments =  { properties: { url: "http://mywebsite.com" } }
Analytics.page(arguments)

but it is throwing error '.name must be a string' 

When I looked in to code 'name' parameter is required 
https://github.com/segmentio/analytics-ruby/blob/master/lib/segment/analytics/client.rb#L217

But according to docs the 'name' is optional parameter
https://segment.com/docs/spec/page/

**Comment by pdlug** [comment]
I'm experiencing the same issue, commenting out line 217 in `lib/segment/analytics/client.rb` fixes this but the library should be fixed.

**Comment by lucasocon** [comment]
I created a pull request to solve this issue.
You can check here: https://github.com/segmentio/analytics-ruby/pull/83
