### ISSUE TITLE
Doesn't work inside rails runner or rake task?

### ISSUE THREAD

**Issue by dseravalli** [segmentio/analytics-ruby#86]
I have a simple import script I'm trying to run with `rails runner -e local /path/to/script.rb` that seems to work but nothing shows up in the Segment debugger. My identify calls return true and error handler is not hit. The same code works if I `load` the file in the rails console.

**Comment by michaeljkchoi** [comment]
I'm not sure if this is the same issue or not, but it doesn't seem to work for ActiveJob either.
```
# app/jobs/foo.rb
class Foo < ActiveJob::Base
  queue_as :high_priority

  def perform
    AnalyticsService.new.track(user_id: "foobar", event: "Foo Bar") # service that calls Segment
  end
end
```

It seems if we run the Job directly `Foo.new.perform` it works as expected.  But if we delay the job with `Foo.perform_later`, then it no longer works.

**Comment by michaeljkchoi** [comment]
Same issue as #77 (closed)

The solution is to call `@analytics.flush` after the track (as per the [docs](https://segment.com/docs/libraries/ruby/#flush))

**Comment by occamin** [comment]
Hey @michaeljkchoi, I'm having the same issue using ActiveJob with Sidekiq even when calling `#flush` after the track. Any suggestions how I might go about debugging this?

Same story with `#perform_now` working but `#perform_later` finishing without emitting the event.

**Comment by michaeljkchoi** [comment]
@occamin - Sorry, I'm not familiar with Sidekiq.  If `#flush` isn't working, maybe it's an issue elsewhere?

**Comment by sperand-io** [comment]
Hey folks — for these sorts of use cases (one off tasks, background jobs, etc) we're recommending [simple_segment](https://github.com/whatthewhat/simple_segment) until we ship a synchronous mode for this gem. Thanks!

**Comment by ravensnowbird** [comment]
This helped me solve the problem. [https://stackoverflow.com/questions/28928560/why-does-http-request-fail-when-running-from-rake-task-in-a-thread](url)

**Comment by shrinathaithal** [comment]
> This helped me solve the problem. [https://stackoverflow.com/questions/28928560/why-does-http-request-fail-when-running-from-rake-task-in-a-thread](url)

You seem to have linked segment github repo for stackoverflow text :) 
Of course, I can copy paste the link text in browser.
