### ISSUE TITLE
User ID is not actually required

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/analytics-ruby#93]
Consider [this line](https://github.com/segmentio/analytics-ruby/blob/eace66e75c015267b62a0f151c43661405e08469/lib/segment/analytics/client.rb#L358)

This doesn't actually require `user_id` or `anonymous_id`, since empty strings are not falsy. I'm not a ruby guy, so I don't actually know the right syntax. (I was just told this by a ruby dev)

**Comment by hankim813** [comment]
I think we can close this because it would be `null` if they were not set.

**Comment by dominicbarnes** [comment]
@hankim813 iirc, the issue is that if you run this library w/o adding `user_id`, the request still fails. (but it shouldn't even get past the line I linked to)

This isn't a critical issue, but it is still a bug.

**Comment by benjaminhoffman** [comment]
https://github.com/segmentio/analytics-ruby/pull/116
