### ISSUE TITLE
Convert snake_cased_keys to camelKeys

### ISSUE THREAD

**Issue by arielvalentin** [segmentio/analytics-ruby#96]
It would be nice if this library would convert snake cased keys and convert them to camel case before sending them off to the API. 

When I send over `created_at` it creates two columns in our Redshift Data Warehouse, one for `created_at` and the other for `traits_created_at`, which I find a bit confusing. I tried to camel case all of the keys, but it seems the Client is checking for specific snake cased keys like 'user_id'. Now I have a code that has to create hashes with different casing strategies for the keys depending on where they are in the hash. 

Also there are certain [Mixpanel](https://help.segment.com/hc/en-us/requests/43888) traits that were not properly mapped.

**Comment by hpoydar** [comment]
Agreed - is there any reason *not* to camel case every key before sending? Seems hokey that I have to track that in my code. (Big PITA with the Intercom integration).

**Comment by sperand-io** [comment]
Hey all, apologies for the misunderstanding here. Our integrations should be normalizing the keys at the transformation layer, allowing for adherence to language conventions like casing, etc. If you ping friends@segment with the issues downstream we'll be sure to get patches lined up for each at the appropriate layer in the stack. Cheers!
