### ISSUE TITLE
Documentation for analytics.track timestamp parameter out of date

### ISSUE THREAD

**Issue by wehriam** [segmentio/analytics-ruby#97]
In the [`track` method docs for `analytics-ruby`](https://segment.com/docs/libraries/ruby/#track) the `timestamp` parameter type is listed as `DateTime` but should be `Time`.

**Current:**

> A DateTime representing when the event took place. If the identify just happened, leave it out and we’ll use the server’s time. If you’re importing data from the past make sure you send a timestamp.

**Suggested:**

> A Time representing when the event took place. If the track just happened, leave it out and we’ll use the server’s time. If you’re importing data from the past make sure you send a timestamp.

Using a `DateTime` throws an argument error:

``` sh
2016-03-23 17:20:16 - ArgumentError - Timestamp must be a Time:
        /XYZ/shared/bundle/ruby/2.1.0/gems/analytics-ruby-2.0.13/lib/segment/analytics/client.rb:324:in 'check_timestamp!'
        /XYZ/shared/bundle/ruby/2.1.0/gems/analytics-ruby-2.0.13/lib/segment/analytics/client.rb:64:in 'track'
        /XYZ/shared/bundle/ruby/2.1.0/gems/analytics-ruby-2.0.13/lib/segment/analytics.rb:19:in 'method_missing'
```

The [docs for the `identify` method](https://segment.com/docs/libraries/ruby/#track) reference `Time`.

**Comment by f2prateek** [comment]
sorry for the delay, we'll update the docs.

**Comment by f2prateek** [comment]
Tracking internally https://segment.atlassian.net/browse/LIB-108

**Comment by rohitpaulk** [comment]
Submitted a PR to the docs repo, keeping this assigned to myself so that I remember to close it.

**Comment by f2prateek** [comment]
Updated now!
